"""Task Status Constants.

定义文件级、产品级、批次级任务状态常量。"""


# ── FileCleaningTask 状态 ──────────────────────────────────────────────
FILE_STATUS_WAITING = "WAITING"
FILE_STATUS_ANALYZING = "ANALYZING"
FILE_STATUS_CLEANING = "CLEANING"
FILE_STATUS_VALIDATING = "VALIDATING"
FILE_STATUS_COMPLETED = "COMPLETED"
FILE_STATUS_FAILED = "FAILED"
FILE_STATUS_SKIPPED = "SKIPPED"

# ── ProductTask 状态 ───────────────────────────────────────────────────
PRODUCT_STATUS_WAITING = "WAITING"
PRODUCT_STATUS_RUNNING = "RUNNING"
PRODUCT_STATUS_COMPLETED = "COMPLETED"
PRODUCT_STATUS_FAILED = "FAILED"
PRODUCT_STATUS_COMPLETED_WITH_ERROR = "COMPLETED_WITH_ERROR"

# ── BatchTask 状态 ─────────────────────────────────────────────────────
BATCH_STATUS_CREATED = "CREATED"
BATCH_STATUS_RUNNING = "RUNNING"
BATCH_STATUS_COMPLETED = "COMPLETED"
BATCH_STATUS_COMPLETED_WITH_ERROR = "COMPLETED_WITH_ERROR"
BATCH_STATUS_FAILED = "FAILED"
BATCH_STATUS_CANCELLED = "CANCELLED"
